name: this is testing CI

on:
  push:
    branches:
      - main

jobs:
  install_node_test_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 Checkout code
        uses: actions/checkout@v4
      - name: Step 2 Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Print Mt Name
        run: echo "Thanap"
  install_node_test_job2:
    needs: install_node_test_job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 2 Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Print Hello
        run: echo "Hello world"
